cmake_minimum_required(VERSION 4.3)
project(labsST C)

set(CMAKE_C_STANDARD 11)



add_executable(labsST main.c)


add_executable(cw_main lab1/classwork/main.c)
add_executable(task1_1 lab1/classwork/task1.1.c)
add_executable(task1_2 lab1/classwork/task1.2.c)
add_executable(task1_3 lab1/classwork/task1.3.c)
add_executable(task1_4 lab1/classwork/task1.4.c)
add_executable(task1_5 lab1/classwork/task1.5.c)
add_executable(task1_6 lab1/classwork/task1.6.c)
add_executable(task1_7 lab1/classwork/task1.7.c)
add_executable(task1_8 lab1/classwork/task1.8.c)
add_executable(task1_9 lab1/classwork/task1.9.c)



add_executable(hw_main lab1/homework/main.c)
add_executable(task1_15 lab1/homework/task1.15.c)
add_executable(task1_20 lab1/homework/task1.20.c)